/**
 * @author Laura Martinez (lauracam@andrew.cmu.edu)
 * Last Modified: March 29, 2013
 * 
 * This is the model of the web application, receives two parameters: a phone number and a message
 */


package edu.andrew.lauracam;

import java.io.OutputStreamWriter;
import java.net.HttpURLConnection;
import java.net.URL;
import java.net.URLEncoder;

public class Sms2PhoneModel {

	// Set Twilio credentials
	public static final String ACCOUNT_SID = "ACe3e0bf28a73ebe4db89a37c75d5678d6"; //"ACfdd433dcc2308ca2ffbb8fc610d1ad30";
    public static final String AUTH_TOKEN = "dd5dcd32e4bdda74054fc07f3130f43c"; //"63c700239b0d6430ea9f4ae65136cc59";
    //TwiML APP SID
    public static final String APP_SID = "APb77fc8ce1e82b6dd8f2e8e2abbe0dd86"; //"APfc8e8d3770ec6809de1dbeb4863926cc";
    //Base 64 encoded ACCOUNT_SID:AUTH_TOKEN
    public static final String AUTH = "QUNlM2UwYmYyOGE3M2ViZTRkYjg5YTM3Yzc1ZDU2NzhkNjpkZDVkY2QzMmU0YmRkYTc0MDU0ZmMwN2YzMTMwZjQzYw=="; //"QUNmZGQ0MzNkY2MyMzA4Y2EyZmZiYjhmYzYxMGQxYWQzMDo2M2M3MDAyMzliMGQ2NDMwZWE5ZjRhZTY1MTM2Y2M1OQ==";
    
    //member variables
    private String phoneNum;
    private String message;
    private String result;
    
    //Default constructor
	public Sms2PhoneModel(){};
	
	/**
     * The doGet method used GET to capture the content from a form in the JSP
     * @param phnNum phone number to make the call
     * @param msg message to be told during the call
     */
	
	public void makeCall(String phnNum, String msg){
		
		//Assign the member variables
		phoneNum = phnNum;
		message = msg;
		
		setTwilioMessage(msg);

        try{

            //Set the Twilio url API that will actually make the call
            URL urlCall = new URL("https://api.twilio.com/2010-04-01/Accounts/" + ACCOUNT_SID + "/Calls");
            
            //Open the connection and use POST to make the call
            HttpURLConnection urlConnectionCall = (HttpURLConnection) urlCall.openConnection();
            urlConnectionCall.setRequestMethod("POST");
            urlConnectionCall.setDoInput(true);
            urlConnectionCall.setDoOutput(true);
            urlConnectionCall.setUseCaches(false);
            
            //Get authorization
            urlConnectionCall.setRequestProperty("Authorization", "Basic " + AUTH);

            /*String userCredentials = APP_SID + ":" + AUTH;
            String basicAuth = "Basic " + new String(new Base64().encode(userCredentials.getBytes()));
            urlConnectionCall.setRequestProperty ("Authorization", basicAuth);*/
            
            
            //Set the parameters of the call: the phone number, the calling number, the method and a experimental param that detects whether the answer is answered by a machine or human
            OutputStreamWriter writerCall = new OutputStreamWriter(urlConnectionCall.getOutputStream());
            writerCall.write("To=" + phoneNum);
            //writerCall.write("&From=" + "4123075528");
            writerCall.write("&From=" + "7737886930");
            writerCall.write("&ApplicationSid=" + APP_SID);
            writerCall.write("&IfMachine=Hangup");
            writerCall.write("&Method=GET");
            writerCall.close();
            
            //Set the status of the call
            if (urlConnectionCall.getResponseCode() == 201){
            	result = "Success! Pick up the phone and press any key to hear your message :)";
            }
            else{
            	result = "Error in the call" + urlConnectionCall.getResponseCode();
            }
            
        }catch(Exception e){
        	result = "Error! Uhoh: " + e.toString();
        }
        
	}
	
	private void setTwilioMessage(String msg){
	
		try{
	    	//Set the Twilio url API that will create the message
	    	URL url = new URL("https://api.twilio.com/2010-04-01/Accounts/" + ACCOUNT_SID + "/Applications/" + APP_SID);
	
	    	//Open the connection and use POST to set the message
	        HttpURLConnection urlConnection = (HttpURLConnection) url.openConnection();
	        urlConnection.setRequestMethod("POST");
	        urlConnection.setDoInput(true);
	        urlConnection.setDoOutput(true);
	        urlConnection.setUseCaches(false);
	        
	        //Get authorization
	        urlConnection.setRequestProperty("Authorization", "Basic " + AUTH);
	        
	        //Pass the parameters to the POST request
	        OutputStreamWriter writer = new OutputStreamWriter(urlConnection.getOutputStream());
	        
	        //Set the message, based on a TwiML generated by the GAE app given the message the user enters.
	        writer.write("VoiceUrl=http://sms2phoneds.appspot.com/?msg=");
	        writer.write(URLEncoder.encode(URLEncoder.encode(message,"UTF-8"), "UTF-8"));
	        writer.write("&VoiceMethod=GET");
	        writer.close();
	
	        //Set the status of the call
            if (urlConnection.getResponseCode() != 200){
            	result = "Error in setting the message";
            }
	        
		}catch(Exception e){
			result = "Error! Uhoh: " + e.toString();
		}
	}
	
	public String getResult() {
		return result;
	}

	public String getPhoneNum() {
		return phoneNum;
	}

	public void setPhoneNum(String phoneNum) {
		this.phoneNum = phoneNum;
	}

	public String getMessage() {
		return message;
	}

	public void setMessage(String message) {
		this.message = message;
	}
	
	
}
